# config file updated 9/12/21

AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true
  StyleGuideBaseURL: https://rubystyle.guide/
  TargetRubyVersion: 3.0

Style/BlockComments:
  Description: 'Do not use block comments.'
  Enabled: False

Style/CommandLiteral:
  Description: 'Use `` or %x around command literals.'
  Enabled: true
  # backticks: Always use backticks.
  # percent_x: Always use %x.
  # mixed: Use backticks on single-line commands, and %x on multi-line commands
  EnforcedStyle: mixed
  SupportedStyles:
    - backticks
    - percent_x
    - mixed
  # If false, the cop will always recommend using %x if one or more backticks
  # are found in the command string.
  AllowInnerBackticks: false

Style/EmptyLiteral:
  Description: Prefer literals to Array.new/Hash.new/String.new.
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  Description: Require the addition of the frozen string literal comment.

Style/GuardClause:
  Description: Check for conditionals that can be replaced with guard clauses.
  Enabled: false

Style/HashSyntax:
  Description: >-
                 Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax
                 { :a => 1, :b => 2 }.
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
  UseHashRocketsWithSymbolValues: false
  PreferHashRocketsForNonAlnumEndingSymbols: false

Style/IfUnlessModifier:
  Description: >-
                 Favor modifier if/unless usage when you have a
                 single-line body.
  Enabled: false

Style/InlineComment:
  Description: Avoid inline comments.
  Enabled: false
